apiVersion: connectors.aiops.ibm.com/v1beta1
kind: BundleManifest
metadata:
  name: testtemplate
spec:
  prereqs:
    repo: 'https://testtemplate.katamari.svc/git/cp4waiops-connectors'
    branch: bundled-version
    authSecret:
      name: cp4waiops-connectors-deploy-auth-secret
    certSecret:
      name: testtemplate-cert-secret
    components:
      - name: deployment
        path: /bundles/connectors/custom/prereqs
        type: kustomize
        kustomization:
          images:
            - name: testtemplate
              newName: icr.io/ibm-aiops-dev/aiopsedge/testtemplatebundle
              newTag: 0.0.1
  instanced:
    repo: 'https://testtemplate.katamari.svc/git/cp4waiops-connectors'
    branch: bundled-version
    authSecret:
      name: cp4waiops-connectors-deploy-auth-secret
    certSecret:
      name: testtemplate-cert-secret
    components:
      - name: connector
        path: /bundles/connectors/custom/connector
        type: kustomize
        kustomization:
          images:
            - name: testtemplate
              newName: icr.io/ibm-aiops-dev/aiopsedge/testtemplatebundle
              newTag: 0.0.1