apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - connectorschema.yaml
  - microedgeconfiguration.yaml
  # - topics.yaml

configurations:
  - custom-images.yaml

images:
  - name: github-sample
    newName: PLACEHOLDER_REGISTRY_ADDRESS/github-sample
    newTag: latest