apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - connectorschema.yaml
  - microedgeconfiguration.yaml

configurations:
  - custom-images.yaml

images:
  - name: ticket-system
    newName: PLACEHOLDER_REGISTRY_ADDRESS/cp/aiopsedge/cp4waiops-connector-ticket-system
    newTag: latest