apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - connectorschema.yaml
  - microedgeconfiguration.yaml
  # - topics.yaml

configurations:
  - custom-images.yaml

images:
  - name: github-grpc-connector-template
    newName: PLACEHOLDER_REGISTRY_ADDRESS/cp/aiopsedge/github-grpc-connector-template
    newTag: latest