apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - serviceaccount.yaml
  - servicemonitor.yaml

configurations:
  - namereference.yaml
  - varreference.yaml

images:
  - name: ticket-system
    newName: docker.io/sghung/ticket-system
    newTag: latest

vars:
  - name: SERVICE_NAME
    objref:
      kind: Service
      name: ticket-system
      apiVersion: v1
    fieldref:
      fieldpath: metadata.name
  - name: SERVICE_NAMESPACE
    objref:
      kind: Service
      name: ticket-system
      apiVersion: v1
    fieldref:
      fieldpath: metadata.namespace
