apiVersion: v1
kind: Service
metadata:
  name: ticket-system
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: ticket-system
  labels:
    app: ticket-system
    instance: connector
spec:
  selector:
    app: ticket-system
    instance: connector
  ports:
    - protocol: TCP
      port: 443
      name: https
      targetPort: 9443
