apiVersion: v1
kind: Service
metadata:
  name: java-grpc-conn-template
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: ticket-template
  labels:
    app: ticket-template
    instance: connector
spec:
  selector:
    app: ticket-template
    instance: connector
  ports:
    - protocol: TCP
      port: 443
      name: https
      targetPort: 9443
