apiVersion: v1
kind: Service
metadata:
  name: github-grpc-conn-template
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: github-grpc-connector-template
  labels:
    app: github-grpc-connector-template
    instance: connector
spec:
  selector:
    app: github-grpc-connector-template
    instance: connector
  ports:
    - protocol: TCP
      port: 443
      name: https
      targetPort: 9443
